P5 E-Learning/force-app/main/default/objects/Option__c/Option__c.object-meta.xml
<CustomObject>
    <label>Option</label>
    <nameField>
        <displayFormat>{00}</displayFormat>
        <label>Option Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

P5 E-Learning/force-app/main/default/objects/Question_Response__c/Question_Response__c.object-meta.xml
<CustomObject>
    <label>Question Response</label>
    <nameField>
        <displayFormat>QR-{0000}</displayFormat>
        <label>Question Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions_Response</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

P5 E-Learning/force-app/main/default/objects/Question_Response__c/fields/Option__c.field-meta.xml
<CustomField>
    <fullName>Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Option</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Option__c.Question__c</field>
            <operation>equals</operation>
            <valueField>$Source.Question__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Option__c</referenceTo>
    <relationshipLabel>Questions_Response</relationshipLabel>
    <relationshipName>Questions_Response</relationshipName>
    <type>Lookup</type>
</CustomField>

P5 E-Learning/force-app/main/default/objects/Question_Response__c/fields/Unit_Response__c.field-meta.xml
<CustomField>
    <fullName>Unit_Response__c</fullName>
    <label>Unit Response</label>
    <referenceTo>Unit_Response__c</referenceTo>
    <relationshipLabel>Questions_Response</relationshipLabel>
    <relationshipName>Questions_Response</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

P5 E-Learning/force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

P5 E-Learning/force-app/main/default/objects/Unit__c/fields/Unit_Score__c.field-meta.xml
<CustomField>
    <fullName>Unit_Score__c</fullName>
    <label>Unit Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

P5 E-Learning/force-app/main/default/objects/Unit_Response__c/Unit_Response__c.object-meta.xml
<CustomObject>
    <label>Unit Response</label>
    <nameField>
        <displayFormat>UR-{0000}</displayFormat>
        <label>Unit Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Units Response</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

P5 E-Learning/force-app/main/default/objects/Unit_Response__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipName>Students_Units</relationshipName>
    <type>Lookup</type>
</CustomField>

P5 E-Learning/force-app/main/default/objects/Unit_Response__c/fields/UserID__c.field-meta.xml
<CustomField>
    <fullName>UserID__c</fullName>
    <formula>Student_Module__r.User__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>UserID</label>
    <type>Text</type>
</CustomField>

P5 E-Learning/force-app/main/default/objects/User/fields/Accumulated_Score__c.field-meta.xml
<CustomField>
    <fullName>Accumulated_Score__c</fullName>
    <label>Accumulated Score</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

P5 E-Learning/force-app/main/default/classes/UnitResponseTrigger.cls
public class UnitResponseTrigger{
    public static void onBeforeUpdate(List<Unit_Response__c> unitRespList, Map<Id,Unit_Response__c> oldUnitRespMap){
        List<Unit_Response__c> answeredUnitRespList = new List<Unit_Response__c>();
        
        for(Unit_Response__c unitResp : unitRespList){
            
            if(unitResp.Stage_Unit_Response__c == 'Answered' && oldUnitRespMap.get(unitResp.Id).Stage_Unit_Response__c == 'Draft'){
                answeredUnitRespList.add(unitResp);
            }
        }
        validateAnswers(answeredUnitRespList);
    }

    public static void onAfterUpdate(List<Unit_Response__c> unitRespList, Map<Id,Unit_Response__c> oldUnitRespMap){
        List<Unit_Response__c> completedUnitRespList = new List<Unit_Response__c>();
        
        for(Unit_Response__c unitResp : unitRespList){
            
            if(unitResp.IsCompleted__c && !oldUnitRespMap.get(unitResp.Id).IsCompleted__c){
                completedUnitRespList.add(unitResp);
            }   
        }
        updateUserPoints(completedUnitRespList);
    }

    private static void updateUserPoints (List<Unit_Response__c> completedUnitRespList){
        //Recolecto UsersIDs en un SET
        Set<Id> usersIds = new Set<Id>();
       
        for(Unit_Response__c unitResp: completedUnitRespList){
            usersIds.add(unitResp.UserID__c);
        }

        //Buscamos usuarios relacionados a las units repsonses
        Map<Id, User> usersMap = new Map<Id, User>([SELECT Id, Accumulated_Score__c FROM User WHERE Id =: usersIds]);

        for(Unit_Response__c unitResp: completedUnitRespList){
            User user = usersMap.get(unitResp.UserID__c);
            user.Accumulated_Score__c += unitResp.Score__c;
        }
        update usersMap.values();
    }

    private static void validateAnswers (List<Unit_Response__c> unitRespList){

        Map<Id,Unit_Response__c> unitRespFromDbMap = new Map<Id,Unit_Response__c>([SELECT Id, Unit__r.Unit_Score__c, (SELECT Id, Option__r.Is_Correct__c FROM Questions_Response__r) FROM Unit_Response__c WHERE Id IN : unitRespList]);


        for(Unit_Response__c unitResp : unitRespList){
            Unit_Response__c unitRespFromDb = unitRespFromDbMap.get(unitResp.Id);

            unitResp.IsCompleted__c = true;
            unitResp.Stage_Unit_Response__c = 'Success';
            for (Question_Response__c questionResp : unitRespFromDb.Questions_Response__r){
                if(!questionResp.Option__r.Is_Correct__c){
                    unitResp.IsCompleted__c = false;
                    unitResp.Stage_Unit_Response__c = 'Fail';
                    break;
                }
            }

            //Seteo los puntos en caso que sea correcta
            if(unitResp.IsCompleted__c){
                if(unitResp.Number_Tries__c == 1){
                    unitResp.Score__c = unitRespFromDb.Unit__r.Unit_Score__c;
                } else if(unitResp.Number_Tries__c == 2){
                    unitResp.Score__c = unitRespFromDb.Unit__r.Unit_Score__c / 2;
                }else {
                    unitResp.Score__c = unitRespFromDb.Unit__r.Unit_Score__c / 4;
                }
            }

        }   
    }
}