P5 E-Learning/force-app/main/default/objects/Module__c/Module__c.object-meta.xml
<CustomObject>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

P5 E-Learning/force-app/main/default/objects/Option__c/Option__c.object-meta.xml
<CustomObject>
    <label>Option</label>
    <nameField>
        <displayFormat>{00}</displayFormat>
        <label>Option Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

P5 E-Learning/force-app/main/default/objects/Option__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

P5 E-Learning/force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

P5 E-Learning/force-app/main/default/objects/Question_Response__c/Question_Response__c.object-meta.xml
<CustomObject>
    <label>Question Response</label>
    <nameField>
        <displayFormat>QR-{0000}</displayFormat>
        <label>Question Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions_Response</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

P5 E-Learning/force-app/main/default/objects/Question_Response__c/fields/Option__c.field-meta.xml
<CustomField>
    <fullName>Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Option</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Option__c.Question__c</field>
            <operation>equals</operation>
            <valueField>$Source.Question__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Option__c</referenceTo>
    <relationshipLabel>Questions_Response</relationshipLabel>
    <relationshipName>Questions_Response</relationshipName>
    <type>Lookup</type>
</CustomField>

P5 E-Learning/force-app/main/default/objects/Question_Response__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Questions_Response</relationshipLabel>
    <relationshipName>Questions_Response</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

P5 E-Learning/force-app/main/default/objects/Question_Response__c/fields/Unit_Response__c.field-meta.xml
<CustomField>
    <fullName>Unit_Response__c</fullName>
    <label>Unit Response</label>
    <referenceTo>Unit_Response__c</referenceTo>
    <relationshipLabel>Questions_Response</relationshipLabel>
    <relationshipName>Questions_Response</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

P5 E-Learning/force-app/main/default/objects/Student_Module__c/Student_Module__c.object-meta.xml
<CustomObject>
    <label>Student-Module</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>Student-Module Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students-Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

P5 E-Learning/force-app/main/default/objects/Student_Module__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Module</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Students-Modules</relationshipLabel>
    <relationshipName>Students_Modules</relationshipName>
    <type>Lookup</type>
</CustomField>

P5 E-Learning/force-app/main/default/objects/Student_Module__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Students_Modules</relationshipName>
    <type>Lookup</type>
</CustomField>

P5 E-Learning/force-app/main/default/objects/Trail__c/Trail__c.object-meta.xml
<CustomObject>
    <label>Trail</label>
    <nameField>
        <label>Trail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

P5 E-Learning/force-app/main/default/objects/Trail_Module__c/Trail_Module__c.object-meta.xml
<CustomObject>
    <label>Trail-Module</label>
    <nameField>
        <displayFormat>TM-{0000}</displayFormat>
        <label>Trail-Module Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trail-Modules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

P5 E-Learning/force-app/main/default/objects/Trail_Module__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <label>Module</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Module__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Trails</relationshipLabel>
    <relationshipName>Trail_Modules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

P5 E-Learning/force-app/main/default/objects/Trail_Module__c/fields/Trail__c.field-meta.xml
<CustomField>
    <fullName>Trail__c</fullName>
    <label>Trail</label>
    <referenceTo>Trail__c</referenceTo>
    <relationshipLabel>Modules</relationshipLabel>
    <relationshipName>Trail_Modules</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

P5 E-Learning/force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

P5 E-Learning/force-app/main/default/objects/Unit__c/fields/Challenge_Type__c.field-meta.xml
<CustomField>
    <fullName>Challenge_Type__c</fullName>
    <label>Challenge Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hands on Challenge</fullName>
            </value>
            <value>
                <fullName>Multiple Choice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

P5 E-Learning/force-app/main/default/objects/Unit__c/fields/Time_Estimate__c.field-meta.xml
<CustomField>
    <fullName>Time_Estimate__c</fullName>
    <label>Time Estimate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

P5 E-Learning/force-app/main/default/objects/Unit__c/fields/Unit_Score__c.field-meta.xml
<CustomField>
    <fullName>Unit_Score__c</fullName>
    <label>Unit Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

P5 E-Learning/force-app/main/default/objects/Unit_Response__c/Unit_Response__c.object-meta.xml
<CustomObject>
    <label>Unit Response</label>
    <nameField>
        <displayFormat>UR-{0000}</displayFormat>
        <label>Unit Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Units Response</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

P5 E-Learning/force-app/main/default/objects/Unit_Response__c/fields/Student_Module__c.field-meta.xml
<CustomField>
    <fullName>Student_Module__c</fullName>
    <label>Student-Module</label>
    <referenceTo>Student_Module__c</referenceTo>
    <relationshipName>Students_Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

P5 E-Learning/force-app/main/default/objects/Unit_Response__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipName>Students_Units</relationshipName>
    <type>Lookup</type>
</CustomField>

P5 E-Learning/force-app/main/default/objects/Unit_Response__c/fields/UserID__c.field-meta.xml
<CustomField>
    <fullName>UserID__c</fullName>
    <formula>Student_Module__r.User__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>UserID</label>
    <type>Text</type>
</CustomField>

P5 E-Learning/force-app/main/default/classes/UnitService.cls
public class UnitService{
    public class CustomException extends Exception{}
    
    public static Boolean registerUnitResponse (Id unitId, String jsonAnswer){

            Savepoint sp = Database.setSavepoint();

        try{
            //Select Unit From DB
            Unit__c unit = [SELECT Module__c, (SELECT Id FROM Questions__r), (SELECT Id, Number_Tries__c FROM Units_Response__r WHERE Student_Module__r.User__c =: UserInfo.getUserId() ORDER BY Number_Tries__c DESC LIMIT 1) FROM Unit__c WHERE Id =: unitId];

            //Check If Module Resp Exist
            Student_Module__c studentMod = [SELECT Id FROM Student_Module__c WHERE Module__c =: unit.Module__c AND User__c =: Userinfo.getUserId() AND Status__c = 'In Progress'];
            
            //If not exist, I create it
            if(studentMod == null){
               studentMod = new Student_Module__c(User__c = Userinfo.getUserId(), Module__c = unit.Module__c, Status__c = 'In Progress');
                insert studentMod;      
            }          

            //Create & Insert of Unit Response
            Unit_Response__c unitResp = new Unit_Response__c(Unit__c = unitId, Student_Module__c = studentMod.Id, Stage_Unit_Response__c = 'Draft');
           
            //Add number of tries
            unitResp.Number_Tries__c = !unit.Units_Response__r.isEmpty() ? unit.Units_Response__r[0].Number_Tries__c + 1 : 1;
            insert unitResp;

            //Create & Insert of Questions Response
            Map<Id,Id> answerMap = (Map<Id,Id>)JSON.deserializeStrict(jsonAnswer, Map<Id,Id>.class);

            List<Question_Response__c> questionRespList = new List<Question_Response__c>();

            for(Question__c question : unit.Questions__r){
                if(answerMap.containsKey(question.Id)){
                    Question_Response__c questionResp = new Question_Response__c(Question__c = question.Id, Unit_Response__c = unitResp.Id, Option__c = answerMap.get(question.Id));
                questionRespList.add(questionResp);
                }else{
                    throw new CustomException('La pregunta'
                    + question.Name + 'no fue respondida y es requerida!');
                }
            
            }
            
            insert questionRespList;
        
            //Update Unit Response with a stage 'Answered' to shoot the Trigger

            unitResp.Stage_Unit_Response__c = 'Answered';
            
            update unitResp;
            
            //ES NECESARIA LA QUERY?? O PODRIMOS SOLO RETORNAR unitResp?
            return [SELECT IsCompleted__c FROM Unit_Response__c WHERE Id =: unitId].IsCompleted__c;

        }catch(Exception e){
            Database.rollback(sp);
            throw e;
        }

    }


    //>>>>>>>>>>>>>>>>>> CLASS TRAIL WRAPPER  !!<<<<<<<<<<<<<<<<<<<
    public class TrailWrapper{
        //Configuration
        public Trail__c trail;
        public List<Module__c> modules;
        
        //Transactional
        public Set<Id> passedModuleIds;
        public Set<Id> passedUnitIds;
        public Double progressTrail;

         //CONSTRUCTOR!
        public TrailWrapper(Trail__c trail, List<Module__c> modules, Set<Id> passedModuleIds, Set<Id> passedUnitIds){
            this.trail = trail;
            this.modules = modules;
            this.passedModuleIds = passedModuleIds;
            this.passedUnitIds = passedUnitIds;
            this.progressTrail = (Double) passedModuleIds.size()*100 /  (Double) modules.size();
        }
    }

    //------------------------ METHODS------------------------
    //___________________PUBLIC___________________

    public TrailWrapper getTrailWrapper(Id trailId){
            //New Instance of TrailWrapper
            TrailWrapper trailWrap = new TrailWrapper([SELECT Name, Description__c, Trail_Time__c, Trail_Score__c FROM Trail__c WHERE Id =: trailId], getModules(trailId), getModuleIdsCompleted(trailId), getUnitIdsCompleted(trailId));
    
            return trailWrap;
        }
    
    //___________________PRIVATE___________________
        private List<Module__c> getModules(Id trailId){
            //Search related modules
            List<Trail_Module__c> trailModules = [SELECT Module__c FROM Trail_Module__c WHERE Trail__c =: trailId];
            
            Set<Id> moduleIds = new Set<Id>();
            for(Trail_Module__c trailModule : trailModules){
                moduleIds.add(trailModule.Module__c);
            }
            return [SELECT Name, (SELECT Name FROM Units__r) FROM Module__c WHERE Id in : moduleIds];
        }
    
        private Set<Id> getModuleIdsCompleted(Id trailId){
            List<Student_Module__c> moduleResponses = [SELECT Module__c FROM Student_Module__c WHERE Status__c = 'Completed' AND Module__c IN : getModules(trailId) AND User__c =: Userinfo.getUserId()];
            Set<Id> completedModuleIds = new Set<Id>();
            for(Student_Module__c moduleResp : moduleResponses){
                completedModuleIds.add(moduleResp.Module__c);
            }
    
            return completedModuleIds;
        }
        private Set<Id> getUnitIdsCompleted(Id trailId){
            List<Unit_Response__c> unitResponses = [SELECT Unit__c FROM Unit_Response__c WHERE IsCompleted__c = true AND UserID__c =: Userinfo.getUserId() AND Unit__r.Module__c IN : getModules(trailId)];
            Set<Id> completedUnitIds = new Set<Id>();
            for(Unit_Response__c unitResp : unitResponses){
                completedUnitIds.add(unitResp.Unit__c);
            }
    
            return completedUnitIds;    
        }

    
    //>>>>>>>>>>>>>>>>>>>> CLASS UNIT WRAPPER  !!<<<<<<<<<<<<<<<<<<<
    public class UnitWrapper{
        //Variables
        public Unit__c unit;
        public List<Question__c> questions;

        //CONSTRUCTOR!
        public UnitWrapper(Unit__c unit, List<Question__c> questions){
            this.unit = unit;
            this.questions = questions;
        }
    }


    //------------------------ METHODS------------------------
    //___________________PUBLIC___________________
    public UnitWrapper getUnitWrapper(Id unitID){

        Unit__c unit = [SELECT Id, Name, Content__c, Time_Estimate__c, Unit_Score__c, Challenge_Type__c FROM Unit__c WHERE Id = :unitID];

        List<Question__c> listQuestions = [SELECT Id, Name, (SELECT Id, Name, Description__c,Is_Correct__c FROM Options__r) FROM Question__c WHERE Unit__c =: unitID];

        return new UnitWrapper(unit, listQuestions);
    }
}